#!/usr/bin/env node
/**
 * Reads .env and writes assets/supabase-config.js
 * Run: npm run generate-config
 *
 * Uses SUPABASE_PROJECT_ID to build the URL:
 *   https://{SUPABASE_PROJECT_ID}.supabase.co
 * Uses SUPABASE_PUBLISHABLE_KEY as the anon key (safe for browser).
 * SUPABASE_SECRET_KEY is NOT written to supabase-config.js (server-only).
 */

const fs   = require('fs');
const path = require('path');

const root    = path.join(__dirname, '..');
const envPath = path.join(root, '.env');
const outPath = path.join(root, 'assets', 'supabase-config.js');

if (!fs.existsSync(envPath)) {
  console.error('ERROR: .env file not found at', envPath);
  process.exit(1);
}

// Parse .env (handles comments, blank lines, quoted values)
const env = {};
fs.readFileSync(envPath, 'utf8').split('\n').forEach(line => {
  line = line.trim();
  if (!line || line.startsWith('#')) return;
  const eq = line.indexOf('=');
  if (eq < 0) return;
  const key = line.slice(0, eq).trim();
  let val = line.slice(eq + 1).trim();
  // Strip surrounding quotes if present
  if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
    val = val.slice(1, -1);
  }
  env[key] = val;
});

const projectId   = env.SUPABASE_PROJECT_ID    || '';
const anonKey     = env.SUPABASE_ANON_PUBLIC    || env.SUPABASE_PUBLISHABLE_KEY || '';
const region      = env.SUPABASE_PROJECT_REGION || '';

if (!projectId) {
  console.error('ERROR: SUPABASE_PROJECT_ID is missing from .env');
  process.exit(1);
}
if (!anonKey) {
  console.error('ERROR: SUPABASE_ANON_PUBLIC is missing from .env');
  process.exit(1);
}
if (!anonKey.startsWith('eyJ')) {
  console.error('ERROR: SUPABASE_ANON_PUBLIC does not look like a JWT (should start with eyJ). Check you copied the anon/public key, not the publishable key.');
  process.exit(1);
}

// Construct URL — standard Supabase format
const supabaseUrl = `https://${projectId}.supabase.co`;

const output = `// PAT 3.0 — Supabase Configuration (auto-generated by scripts/generate-config.js)
// DO NOT EDIT MANUALLY — edit .env and re-run: npm run generate-config
// THIS FILE IS GITIGNORED. Never commit it.

const SUPABASE_URL      = '${supabaseUrl}';
const SUPABASE_ANON_KEY = '${anonKey}';
`;

fs.writeFileSync(outPath, output, 'utf8');
console.log('✓ Generated assets/supabase-config.js');
console.log(`  URL:  ${supabaseUrl}`);
console.log(`  Key:  ${anonKey.slice(0, 20)}… (${anonKey.length} chars)`);
if (region) console.log(`  Region: ${region}`);
console.log('\nNOTE: SUPABASE_SECRET_KEY is NOT written to this file (server-only).');
